//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpgTimerWeb2.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EpgTimerWeb2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   /*!
        /// * Bootstrap v3.2.0 (http://getbootstrap.com)
        /// * Copyright 2011-2014 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// */
        ///
        ///if (typeof jQuery === &apos;undefined&apos;) { throw new Error(&apos;Bootstrap\&apos;s JavaScript requires jQuery&apos;) }
        ///
        ////* ========================================================================
        /// * Bootstrap: transition.js v3.2.0
        /// * http://getbootstrap.com/javascript/#transitions
        /// * ========================================================================
        /// * Co [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BootStrap {
            get {
                return ResourceManager.GetString("BootStrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /*!
        /// * Bootstrap v3.2.0 (http://getbootstrap.com)
        /// * Copyright 2011-2014 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// */
        ///
        ////*! normalize.css v3.0.1 | MIT License | git.io/normalize */
        ///html {
        ///  font-family: sans-serif;
        ///  -webkit-text-size-adjust: 100%;
        ///      -ms-text-size-adjust: 100%;
        ///}
        ///body {
        ///  margin: 0;
        ///}
        ///article,
        ///aside,
        ///details,
        ///figcaption,
        ///figure,
        ///footer,
        ///header,
        ///hgroup,
        ///main,
        ///nav,
        ///section,
        ///summary {
        ///  display: block;
        ///}
        ///audio,        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BootStrapStyle {
            get {
                return ResourceManager.GetString("BootStrapStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] glyphicons_halflings_regular_eot {
            get {
                object obj = ResourceManager.GetObject("glyphicons_halflings_regular_eot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] glyphicons_halflings_regular_svg {
            get {
                object obj = ResourceManager.GetObject("glyphicons_halflings_regular_svg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] glyphicons_halflings_regular_ttf {
            get {
                object obj = ResourceManager.GetObject("glyphicons_halflings_regular_ttf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] glyphicons_halflings_regular_woff {
            get {
                object obj = ResourceManager.GetObject("glyphicons_halflings_regular_woff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   /* NUGET: BEGIN LICENSE TEXT
        /// *
        /// * Microsoft grants you the right to use these script files for the sole
        /// * purpose of either: (i) interacting through your browser with the Microsoft
        /// * website or online service, subject to the applicable licensing or use
        /// * terms; or (ii) using the files as included with a Microsoft product subject
        /// * to that product&apos;s license terms. Microsoft reserves all other rights to the
        /// * files not expressly granted by Microsoft, whether by implication, estoppel
        /// * or otherwise. Ins [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JQuery {
            get {
                return ResourceManager.GetString("JQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap loader {
            get {
                object obj = ResourceManager.GetObject("loader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   //EpgDataCap_Bon
        ///$(document).ready(function () {
        ///    $(&quot;button[data-toggle=&apos;tooltip&apos;]&quot;).tooltip();
        ///    $(&quot;button[data-target=&apos;#infoInner&apos;]&quot;).click(function () {
        ///        $(&quot;#infoInner&quot;).collapse($(&quot;#epgInner&quot;).hasClass(&quot;col-sm-12&quot;) ? &quot;show&quot; : &quot;hide&quot;);
        ///        if ($(&quot;#epgInner&quot;).hasClass(&quot;col-sm-12&quot;)) {
        ///            $(&quot;#epgInner&quot;).removeClass(&quot;col-sm-12&quot;).addClass(&quot;col-sm-8&quot;);
        ///            $(&quot;button[data-target=&apos;#infoInner&apos;] span&quot;).removeClass(&quot;glyphicon-chevron-down&quot;).addClass(&quot;glyphicon-chevron-up&quot;);
        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap NotThumbnail {
            get {
                object obj = ResourceManager.GetObject("NotThumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   /* NUGET: BEGIN LICENSE TEXT
        /// *
        /// * Microsoft grants you the right to use these script files for the sole
        /// * purpose of either: (i) interacting through your browser with the Microsoft
        /// * website or online service, subject to the applicable licensing or use
        /// * terms; or (ii) using the files as included with a Microsoft product subject
        /// * to that product&apos;s license terms. Microsoft reserves all other rights to the
        /// * files not expressly granted by Microsoft, whether by implication, estoppel
        /// * or otherwise. Ins [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Respond {
            get {
                return ResourceManager.GetString("Respond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   body {
        ///            padding-top: 100px;
        ///        }
        ///
        ///        #records, #reserves {
        ///            max-height: 300px;
        ///            overflow: auto;
        ///        }
        ///
        ///        #inner table {
        ///            max-width: 150px;
        ///        }
        ///
        ///        #refresh {
        ///            cursor: pointer;
        ///        }
        ///
        ///        #loading {
        ///            position: fixed;
        ///            top: 0px;
        ///            left: 0px;
        ///            background: rgba(0, 0, 0, 0.30);
        ///            width: 100%;
        ///            height: 100%;
        ///            z-index: 9999; [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
    }
}
